language: android
android:
  components:
  - platform-tools
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
script:
- "./gradlew build jacocoTestReport --stacktrace"
before_install:
- chmod +x gradlew
branches:
  only:
  - master
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: 1lg88VVpyaBa1LQJYOk/JnKwCBsmcHumJJSyKgpIfyLGB5KtJl8xlJbTUBQnPVRlLgspkVUuy7NU+4EiINANlGTFkmnr2zCCrZV5EHezaStQ0IJmUzYw+UjCMeqpsZcudulPnLNTScR4Kw2mfHI1SOegGw79Y87y0hmmcA/y5gaNXjH9g4T3/kp1AuC1hj0zFDVZTNjB+QeKQW9fmLm43p789pkTH/w40ef9eo6Eh3yoehObTP3cu/6trilLnC6XdVtcr0ZN14QN5HUOCGFE95f8xPFkRgtB0Mb1Aiy04zIbT0xc4qsp16Z+9ees8t5a9w45VOPikgSSdresgH7Jnr4+euzw8dShccFw+ymyg5+SBDxKkI11HUhRAreDODXESxleLI39IY8VaQhnEJMyAR8lnxqM+7uyLzwD2v/E/OsM0KNsp04JiF6gunsJ1O/zoz3ldy4ykOV/iMSaYH8PWYlgLru3Q2mTipffVkXz+p4R9nQGre3/xQDMro5uSpIheIinIqvNodkuSBXSTZ0Y08qEIds0gAk3WaMc7v5wSTkz3BKrq0/SHZwyDEXga4VmhC24ZE4659DxvBT1BesmdSJAUrzv1npes7qd7Rh0u4lu6CF8uLozKbRYQ4jLHDSebwEO2qTl9LwlI+q7S0jaxl3TKlDWM2F+cSMD57jT9y0=
